### ISSUE TITLE
[DEV] Spellscript questions

### ISSUE THREAD

**Issue by gengarshadowball** [azerothcore/forum#104]
## Hi!

I've been reading the spellscript class and I find the comments confusing so I'm hoping someone can help me understand this core feature.
So far I've been reading a bit of the spellscript class and I found another class which is aurascript. 

1. What are the main differences between 'spellscript' and 'aurascript'?
2. On the 'spellscript' there's usually a function called 'Register' and this is usually to add an "effect" to a hooklist. for example:
`OnEffectHitTarget += SpellEffectFn(spell_warl_soulshatter_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);`
What is happening on the core when this happens?

3. Can you explain the aproach to trying to script a spell? (For example how to apply an aura after X spell has been cast)

I know my questions are quite vague but I'm trying to make sence of something I don't quite understand.
Thanks for any help!

**Comment by Yehonal** [comment]
1) SpellScripts contains the aurascript system. Essentially the aura is something generated by a spell. 

2) the effect is an action that happens at certain time of the spell "life cycle", depending on the effect itself

3) If you go to the ScriptMgr.h file you can see that there are some hooks under the SpellSC class. Those hooks can be used to intercept spell events and eventually change the normal behaviour. If you need more hooks for your scripts that are not available there, you can create a new one.

**Comment by gengarshadowball** [comment]
Thanks for clarification!
