### ISSUE TITLE
[GENERAL] CmakeErrorC1083

### ISSUE THREAD

**Issue by TheDdraig** [azerothcore/forum#106]
Hey, sorry if this is a silly question but im having issues with cmake with the configure/generate getting the following error:
F:\WoWP\Acore\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [F:\WoWP\Acore\Build\CMakeFiles\CMakeTmp\cmTC_f6bdd.vcxproj]

**Comment by FrancescoBorzi** [comment]
Hi @TheDdraig welcome, the forum is not the best place to ask for support.

Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
