### ISSUE TITLE
[DEV]How do I make a quest that is only available after you kill the last boss of a dungeon?

### ISSUE THREAD

**Issue by nickolayis** [azerothcore/forum#110]

**Comment by Kitzunu** [comment]
You'd have to make a condition with the `conditions` table

**Comment by nickolayis** [comment]
Ty btw. Which condition do i alter for quest?

> You'd have to make a condition with the `conditions` table

Which condition do I alter for quest? TY BTW

**Comment by Kitzunu** [comment]
check the Wiki, there should be a SourceType for Quest Available and a Condition for CONDITION_NEAR_CREATURE

Check for CONDITION_NEAR_CREATURE = dead. I am not 100% this works, perhaps you'd need to make a core script for it

**Comment by nickolayis** [comment]
> check the Wiki, there should be a SourceType for Quest Available and a Condition for CONDITION_NEAR_CREATURE
> 
> Check for CONDITION_NEAR_CREATURE = dead. I am not 100% this works, perhaps you'd need to make a core script for it

u da boss
