### ISSUE TITLE
[CLIENT-MOD] Sending Patches To The Client Through The WoW Application

### ISSUE THREAD

**Issue by SamuelGogarty** [azerothcore/forum#118]
Has anyone gotten the following working with AzerothCore?
Would love to see this ported.
https://github.com/stoneharry/Blizzard-Updater
and the documentation can be found here
https://www.dropbox.com/s/fovh9mtrj9tgqd4/Implementing%20in-client%20patching%20for%20World%20of%20Warcraft.pdf?dl=0

**Comment by gengarshadowball** [comment]
The question is, why would you want to modify the client? This takes so much work that I doubt anyone but a dedicated private server would bother doing this.

**Comment by Helias** [comment]
Why? to add custom content.
[Like a custom bg.](https://github.com/azerothcore/mod-bg-slaveryvalley)

**Comment by SamuelGogarty** [comment]
> The question is, why would you want to modify the client? This takes so much work that I doubt anyone but a dedicated private server would bother doing this.

so much work? its 2, documented commands in a wow client patcher program.
