### ISSUE TITLE
[DEV] looking for morph armor free (all races)

### ISSUE THREAD

**Issue by Helias** [azerothcore/forum#119]
I am looking for all creature model IDs "armor free".
What do I mean with "armor free"?

There are some morphs that allow you to keep the items changing your race.

**Example: 20317 = dwarf male**
Using `.morph target 20317` I can morph myself into a dwarf male keeping my equipe.

before the morph:
![image](https://user-images.githubusercontent.com/519778/84439566-bb600680-ac38-11ea-8ca3-0d46847c157f.png)

after the morph:
![image](https://user-images.githubusercontent.com/519778/84439703-ffeba200-ac38-11ea-904d-a937b1b4a30b.png)

So far I found all these model IDs:
```
MALE_FEL_ORC     = 21267
FEMALE_ORC       = 20316

MALE_DWARF       = 20317,

MALE_NIGHT_ELF   = 20318

FEMALE_DRAENEI   = 20323
MALE_BROKEN_DRAENEI = 21105

MALE_TROLL       = 20321,

MALE_HUMAN       = 19723
FEMALE_HUMAN     = 19724

MALE_BLOOD_ELF   = 20578
FEMALE_BLOOD_ELF = 20579

FEMALE_GNOME     = 20320
MALE_GNOME       = 20580

FEMALE_TAUREN    = 20584
MALE_TAUREN      = 20585
```

So I am missing the followings:
```
MALE_ORC
FEMALE_DWARF
FEMALE_TROLL
MALE_DRAENEI
FEMALE_NIGHT_ELF
```

Anyone can help me?

**Comment by Yehonal** [comment]
+1

Maybe in you can find something in DBC about such models

**Comment by BarbzYHOOL** [comment]
check cfbg module?
check orb of deception?

**Comment by BarbzYHOOL** [comment]
can also check some items/spells from here https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/60036142?page=1

**Comment by Helias** [comment]
> check cfbg module?
I am making this to improve the cfbg module.

Thanks for suggestions, I will see :wink:

**Comment by BarbzYHOOL** [comment]
Found displayid 31754 and 31753 that keeps the weapons (but only the weapons)
same for 31681 31663 in fact there are tons in creature_model_info but can't find exactly what u want

Ok found a solution for you while writing this:
Test ALL the IDs listed by this query

```sql
SELECT *
FROM `creature_model_info`
WHERE `DisplayID` IN (21267,20316,20317,20318,20323,20321,19723,19724,20578,20579,20320,20580,20584,20585)

OR `DisplayID_Other_Gender` IN (21267,20316,20317,20318,20323,20321,19723,19724,20578,20579,20320,20580,20584,20585)
LIMIT 50
```

**Comment by BarbzYHOOL** [comment]
hmm it doesn't seem to find the ones you're missing lol, the newest found are the same exact as other IDs (ex: tauren male, female blood elf :'()

**Comment by BarbzYHOOL** [comment]
20582 = goblin male hehe it works
20583 = goblin female

**Comment by BarbzYHOOL** [comment]
ok another try i've made with that query
```sql
SELECT * FROM `creature_template` WHERE `name` LIKE '%male illusion%' LIMIT 50
```
but not the results u wanted

**Comment by BarbzYHOOL** [comment]
Rofl try:

.morph target 56   so ugly!!!

23961 = naked orc (there are more like these with different beards) but can't wear anything bug weapons


Ok so conclusion: i think there is NO solution to what you want

Why? because i checked for male orc and night elf female inside CreatureDisplayInfoExtra and CreatureDisplayInfo and for some genders, there is no entry in CreatureDisplayInfo like u want

**Comment by BarbzYHOOL** [comment]
This one could replace the male Draenei, it's a male Broken:
.morph target 21105

(there is no equivalent for women)

There is no women fel orc either for this kind of thing

**Comment by chamorrorenzo** [comment]
sadly theres is no armor free illusion for every race, the only solution is to make an MPQ

**Comment by Helias** [comment]
This is the result of what I have done with this research, thank you all.
https://github.com/azerothcore/mod-cfbg/pull/21

If we find "similar" morph armor-free like FEL_ORC or BROKEN_DRAENEI I will improve this randomization, but so far I didn't find any good alternatives

**Comment by BarbzYHOOL** [comment]
you won't find others, you can only choose already equiped NPCs or use the opposite gender or just another race :D

i guess I can close this
