### ISSUE TITLE
[GENERAL] common.lib  errors on compiling

### ISSUE THREAD

**Issue by louiebhz** [azerothcore/forum#126]
Hey guys! 

First of all i'd like to say that i'm new in all this programming thing. 

I'm tryng to compile a azeroth core wow server and i'm getting this errors massages.

![image](https://user-images.githubusercontent.com/69588154/90020785-b80fe800-dc86-11ea-9638-68c8141766f5.png)

Can someone help me?

**Comment by FrancescoBorzi** [comment]
hello and welcome!

the forum is not the right place to ask for help, please read this topic and we'll be glad to help you!

https://www.azerothcore.org/wiki/How-to-ask-for-help
