### ISSUE TITLE
[GENERAL] Connecting to Private server from blizzard digital download?

### ISSUE THREAD

**Issue by edjumacator** [azerothcore/forum#134]
Hey team,

I have just recently come across Azerothcore and am eager to host my own server. I'm a Dev-Ops engineer by trade so I understand how to setup my digital ocean droplet using docker. However, I'm curious if there is a way to connect to my private server using a digital copy of WoW I just downloaded from Blizzard. I have 4 DVD's (Classic - Cataclysm) but I just didnt build my new computer with a DVD player (lol) so I figured before I go buy / install a DVD player if there was a way to use the digital copy to point at my server. Thanks in advance for any time / help provided.

**Comment by FrancescoBorzi** [comment]
hello @edjumacator , AzerothCore is compatible only with the version 3.3.5a

**Comment by edjumacator** [comment]
> hello @edjumacator , AzerothCore is compatible only with the version 3.3.5a

Is there a way to get that version online or am I out of luck?

**Comment by FrancescoBorzi** [comment]
sorry, we can't provide downloads to copyrighted material
