### ISSUE TITLE
[DEV] Question about the "creature_text_locale" table.

### ISSUE THREAD

**Issue by arnaucastellvi** [azerothcore/forum#138]
(Excuse my lousy English)

I'm investigating the subject of locations, and I've noticed that the localized text that creatures say (For example, "you no take candle!" from the Kobolds) corresponds to the table "broadcast_text_locale", called by the field "BroadcastTextId" from the table "creature_text".
If I change something there, it is reflected in the game.

My question is: What is the purpose of the table "creature_text_locale"?

**Comment by BarbzYHOOL** [comment]
i don't know, it's pure shit from my profane eyes

I found some old TC commit and my conclusion is that they intended to move everything from that table to broadcast_text_locale and never did it. But then there are still some differences between the tables

This looks like total duplicate data to me

**Comment by BarbzYHOOL** [comment]
maybe @yehonal @rochet2 @kaev have an idea

(Can't unassign myself, github doesn't care about older browsers, can't use any javascript lol)

**Comment by arnaucastellvi** [comment]
After some tests, I can confirm that the table "create_text_locale" is used when "create_text" points to a non-existent "BroadcastTextId" in "broadcast_text_locale".

So if the tables "create_text" and "broadcast_text_locale" are correct, "create_text_locale" is unnecessary.
(In fact, "create_text_locale" is empty)
