### ISSUE TITLE
[DEV] AzerothCore Docker, can't detach after a 'docker-compose up'.

### ISSUE THREAD

**Issue by arnaucastellvi** [azerothcore/forum#139]
After the 'docker-compose up' command, I cannot detach. with 'ctrl+p' and 'ctrl+q' (accessing directly  or via ssh ).
I can detach closing the ssh console, and open again to continue.
Using  "docker attach" to run commands, ctrl+p and ctrl+q, work fine.

Can I detach after do an  'docker-compose up'?

**Comment by FrancescoBorzi** [comment]
welcome @arnaucastellvi , this is not the right place to ask for such technical help. Please read:

https://www.azerothcore.org/wiki/How-to-ask-for-help
