### ISSUE TITLE
How to install module such as mod-npc-buffer

### ISSUE THREAD

**Issue by nyeinchanhtoo-n4g** [azerothcore/forum#141]
Hi Sir,

I already run server with azerothcore n4group.net realm is already running.

I use Ubuntu 18.04 and MySql 5.7

I want to know how to install module such as mod npc buffer ,

Someone teach me step by step and please answer below question

when i run ./acore-installer  No. 7 to search module and then No. 8 to install module and then what menu I choose for active module No.1? its reinstall my server right? data will be delete or not.

or 

I must be install module before installing the server core

Please tell me step by step 

sorry for my bad English writing skill

Thank you very much. >> azerothcore.org

Best regards,
Nyein Chan Htoo
Yangon, Myanmar

**Comment by FrancescoBorzi** [comment]
@nyeinchanhtoo-n4g welcome! the forum is not the right place to ask for support,

please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
