### ISSUE TITLE
[DEV] Keira 3.0.1 test release

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/forum#147]
Please help us testing the upcoming release of Keira3 by downloading the pre-release and letting us know your feedback here **in this thread**.

Keira 3.0.1-beta download: https://mega.nz/folder/04py1TIR#Ot65BkkM9u0hoI9HFCJDiw

**Comment by Winfidonarleyan** [comment]
Perfect work

![image](https://user-images.githubusercontent.com/18329778/99195886-31096900-27bb-11eb-909c-668076363fe1.png)
