### ISSUE TITLE
db_assambler.sh not working

### ISSUE THREAD

**Issue by darkness3285** [azerothcore/forum#16]
![asdfvvvvv](https://user-images.githubusercontent.com/48915406/55291539-f2405880-53b5-11e9-82cd-cdcef43f5b98.PNG)

from this part I do not understand the procedure, I know that I need to do something, but it does not explain exactly.

**"Use the AzerothCore Database Assembler
Move to azerothcore/bin/db_assembler/.

run the db_assembler.sh script:

bash ./db_assembler.sh

it will generate the databases under the /bin/db_assembler/output directory of your azerothcore sources directory."**

**Comment by FrancescoBorzi** [comment]
@darkness3285 for support requests please use Stackoverflow. Please read:

http://www.azerothcore.org/wiki/How-to-ask-for-help

Tip: you should run the command **from your main source directory** using `bin/acore-db-asm` command.

If you still have troubles, please open an issue on stackoverflow (don't comment here).
