### ISSUE TITLE
It can not be this ...

### ISSUE THREAD

**Issue by darkness3285** [azerothcore/forum#17]
There is no one who can tell me how to use the db_assembler.sh, the wiki guides are non-existent, they confuse more instead of helping.
Thank you

**Comment by FrancescoBorzi** [comment]
@darkness3285 please open a question on Stackoverflow and I will be happy to help you.

Please be specific about what you don't understand so we can better explain.

Here's a guide about how to ask: http://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by darkness3285** [comment]
Thanks I have solved it, the big google helped me
