### ISSUE TITLE
the blood bar display is too low

### ISSUE THREAD

**Issue by zhouxinqio** [azerothcore/forum#23]
After pressing V, the blood bar display is too low, blocking the line of sight

**Comment by FrancescoBorzi** [comment]
?

**Comment by poszer** [comment]
I don't understand..

**Comment by Kitzunu** [comment]
I believe the Health Bar you see over Enemies (or allies) if you press V or Ctrl + V ingame, however I dont know how that could block LoS?

**Comment by wizzymore** [comment]
If you have the stacking or overlaping ( i think the overlaping) nameplates on, yeah, this will happen

**Comment by BarbzYHOOL** [comment]
it's client side in top of that and the author doesn't come back
