### ISSUE TITLE
[DEV] Creatures movement issues (Need info)

### ISSUE THREAD

**Issue by poszer** [azerothcore/forum#25]
I'll use this topic, to get from people who know some creature Guids with this movement/fall problem.
So, if you know any just write it in comment:
Example : .go c 2564

**Info** : Need this, coz i'm working to fix this, and it's kinda hard to check every creature alone. So i need your help guys, I'm sure some of you already face this problem. :smiley:  Thanks

Example (Before)
![before](https://user-images.githubusercontent.com/41213210/56205133-38015000-6049-11e9-85ef-ea866f1e3587.png)

Example (After)
![after](https://user-images.githubusercontent.com/41213210/56205157-49e2f300-6049-11e9-9fc0-b3fff4db4d66.png)

**Comment by Pondaveia** [comment]
This is possible related to (this topic)[https://github.com/azerothcore/forum/issues/24#issue-433508386]

**Comment by Stoabrogga** [comment]
A few of the NPCs in Dalaran who have waypoint movement sometimes float through the air or drop through the ground, e.g.:
- Warp-Huntress Kula (32711)
- Great Hexer Ohodo (32719)

It's not happening regularly, though.

**Comment by Stoabrogga** [comment]
Another one in Stormwind City, dropping through a bridge: Officer Brady (14439)
