### ISSUE TITLE
[CLIENT-ADDON] Customer Support

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/forum#29]
I have no idea if this is the right place for this, but here goes;

Does anyone know where in the client files you can change the info which is shown in the Customer Support tab in-game (by pressing ? > Talk to a GM)

I have found where to change the information which is given if you try to login to the game while banned but cannot seem to find where to edit this.

Any help is appreciated, thank you!

**Comment by BarbzYHOOL** [comment]
Ask on model-changing or modcraft but it's probably in the interface files (lua strings)

**Comment by Kitzunu** [comment]
kk thanks,
I checked the LUA strings but couldnt find it D:

**Comment by Kitzunu** [comment]
Just FYI if anyone wants to know about this, the strings are found in the MPQ Patches Interface\FrameXML\GlobalStrings.lua however I could for some reason not get any changes from there to show in-game.

Haven't had much time to look into why, not even with a newer patch which should override the old GlobalStrings.lua.

**Comment by BarbzYHOOL** [comment]
If it's there, then it's there to edit it. Prob a mistake in your MPQ order or whatever

Also recently i saw a DBC that was related to gmticket

**Comment by Kitzunu** [comment]
Thats the weird part, cuz I had two people confirming that the mpq order and layout were correct.

As for the DBC file, I dont think it would have anything with it to do
