### ISSUE TITLE
WoW Background image hunt for Keira3

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/forum#34]
I'm working hard on [Keira3](https://github.com/azerothcore/Keira3) and its first release is behind the corner. Since my time is always limited (and my design skills are not that great), I'm sharing this task with the community since anyone can help with it.

This image:

https://github.com/azerothcore/Keira3/blob/ddbe2a00b937e7cb4af7986d11e8b8a8e4181eba/src/assets/img/bg1.jpg

Is currently the background of the sidebar of Keira3:

![image](https://user-images.githubusercontent.com/75517/59631138-65e93a80-9147-11e9-9dfe-db63825acd2a.png)

Now I would like to replace it with something more AC and/or WoW related. I will select initially one image (but in future I could put a group of images, each time choosing randomly among team at Keira3 startup) to be the new background image of the sidebar.

I was thinking about some screenshot taken in game of some nice landscape, view, or whatever... but I'm open to any suggestions. 

Requirements:

- The image size (width and height) should be approximately the same as the current one, otherwise it doesn't fit well
- The smaller file size the better (currently is 40 KB)
- The colours should fit with its usage (dark in the top, a bit lighter in the bottom... well, you got what I mean)

Would you like to help me selecting a new image (or a group of images)?

Please post your suggestions!

## How to test images

1) Run Keira3 in development mode (instructions available [here])(https://github.com/azerothcore/Keira3#development)

2) Add your image(s) in the `src/assets/img/` directory

3) Change this line of code to try different images https://github.com/azerothcore/Keira3/blob/master/src/app/components/main-window/sidebar/sidebar.component.html#L5

Keira will automatically recompile and show your image.

**Comment by talamortis** [comment]
http://sarahgreve.weebly.com/uploads/1/3/0/3/13033678/5819516_orig.jpg

**Comment by FrancescoBorzi** [comment]
@talamortis nice, but I think it should be a bit darker in the top part:

![image](https://user-images.githubusercontent.com/75517/59638845-c2555580-9159-11e9-9910-a7680072f539.png)

**Comment by BarbzYHOOL** [comment]
**avoid copyrighted artworks too**

**Comment by talamortis** [comment]
it was just something i found on the internet >.<

**Comment by BarbzYHOOL** [comment]
ye ye, but it's copyrighted

who works on a WOW server? not me

PROVE IT :rofl:

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/59696137-591a2480-91e3-11e9-8555-6c84802330ea.png)
 errrm....

**Comment by BarbzYHOOL** [comment]
it's an emulator, not a server

**Comment by talamortis** [comment]
Maybe so but if it wasn't illegal why are blizzard closing server down?

**Comment by FrancescoBorzi** [comment]
@talamortis @BarbzYHOOL I added the instructions in the original post about how to test different background images in Keira3

**Comment by Viste** [comment]
![Снимок экрана от 2020-03-30 02-25-07](https://user-images.githubusercontent.com/281977/77864033-091ac480-722f-11ea-90d3-6a3fd66fcf3a.png)
![Снимок экрана от 2020-03-30 02-22-32](https://user-images.githubusercontent.com/281977/77864034-0a4bf180-722f-11ea-8180-0448be37740a.png)
![Снимок экрана от 2020-03-30 02-15-49](https://user-images.githubusercontent.com/281977/77864035-0b7d1e80-722f-11ea-9694-01e706fd4ef5.png)
all samples in discord

**Comment by BarbzYHOOL** [comment]
maybe first one because it's good for visibility + it's a character so it looks like wow
