### ISSUE TITLE
[DEV] Updating dbc/maps on wowgaming

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/forum#38]
@FrancescoBorzi , @BarbzYHOOL or anyone is interested, we should upgrading the client files in wowgaming client-data repository:

https://github.com/wowgaming/client-data

we've to create a new release with an attached zip called "data.zip"

Such as in this release: https://github.com/wowgaming/client-data/releases

The files must be extracted from a **VERY CLEAN EN-US CLIENT** with our extracting tools using default configuration.

**If you know any link with such files please link them here** and i'll upload them on that repository, otherwise i can add you in wowgaming team allowing you to upload your files there.

In the end we've to update following link with latest version: https://github.com/azerothcore/azerothcore-wotlk/blob/8f12eb031165bcfcb2036423c4b91289cb00de99/apps/installer/includes/functions.sh#L205

In this way AzerothCore will be able to download latest client file via our console dashboard (CLI)

**Comment by Kaev** [comment]
Wouldn't it make more sense to create a repo for that under the AzerothCore organization?
It makes no sense to offer them under "wowgaming" when they can't be used by e.g. TrinityCore and MaNGOS.

**Comment by Yehonal** [comment]
We MUST not include in AZeroThCore any kind of client data directly extracted from it.
AZeroThCore is mainly a MMO server framework and any kind of client data must be extracted externally.
WoWGaming is an organization created to share information and technical data about wow game. In past WoWGaming already had some eula notification about blizzard that has been solved then.

So, if we want to continue to develop this project as an educational project and/or as a server application, we cannot develop an "emulator" but a modular agnostic framework instead.

However i've uploaded new data: https://github.com/wowgaming/client-data/releases/tag/v6

**Comment by BarbzYHOOL** [comment]
new data that is the same as previously??

**Comment by BarbzYHOOL** [comment]
yeah why not

**Comment by FrancescoBorzi** [comment]
@Yehonal are you sure?

![image](https://user-images.githubusercontent.com/75517/62476678-c724a600-b7a7-11e9-8733-e409d4d934b6.png)

**Comment by Yehonal** [comment]
Sure about what?
