### ISSUE TITLE
[DEV] Money for kill

### ISSUE THREAD

**Issue by AzuriaFR** [azerothcore/forum#41]
hi how i can change level max for drop money monster i see i can only drop in the monster 80 and i want add all level 1 -> 80 for drop money thx !

i am Raphtalia#3392 in discord

**Comment by Helias** [comment]
If you are talking about this module [mod-money-for-kills](https://github.com/azerothcore/mod-money-for-kills), just open a issue in that repository and close this.

If you are talking about the Azerothcore worldconfig try to solve with that module or just request (or improve yourself) it to handle your request :wink:
