### ISSUE TITLE
[FEATURE] Additional option for worldserver config parameter "InstantFlightPaths"

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/forum#42]
Currently the worldserver parameter "InstantFlightPaths" allows two options:
0: Instant flight paths off (default behaviour)
1: Instant flight paths on

I'd like to add a third option, as sometimes the player just wants to enjoy the view of the flight, but not always:
2: Player can choose if instant flight is off or on

My idea was to inject an additional gossip menu item for flight masters if option "2" is specified. The menu item is just used to toggle between instant flight on and off. I sadly have no idea how to accomplish this or if it is possible and feasible at all. Could someone perhaps provide a hint on this?

**Comment by BarbzYHOOL** [comment]
good idea and why do you say you don't know if it's possible ? I mean I don't know in details but what about those modules and NPC that do stuff with gossip menu ? you can do it in C++ (i know you're a SAI expert that's why)

**Comment by Stoabrogga** [comment]
Creating a custom CreatureScript is easy, but the flight masters are generic. Their gossip menu and behaviour seem to be specified in Player.cpp:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L14906
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L15122

Sadly, I have no idea how to override this behaviour or how to add an additional gossip option for them.

**Comment by Stoabrogga** [comment]
Ok, figured out a solution myself:
https://github.com/azerothcore/azerothcore-wotlk/pull/2246
