### ISSUE TITLE
[Request] Update GuardDog Script/Make a Module of it

### ISSUE THREAD

**Issue by IceNet** [azerothcore/forum#44]
**Is your feature request related to a problem? Please describe.**
The script works, but it doesn't recognize the target and sets it to its own char

**Describe the solution you'd like**
the script should mark the target with .gd warn char (in authDB, GuardDog = 1, GuardWarnings = +1) and in a gmannouncement
when the char comes online, should also show the name (currently :%s)

**Describe alternatives you've considered**
none. i have no knowledge in c++

**Additional context**
Feature idea: set the comment to the .playerinfo
Script: https://gist.github.com/Coresurgeon/96806bbb88bfbf4b4fff
https://i.imgur.com/TQ62X5N.jpg

**Comment by BarbzYHOOL** [comment]
o_0 hard to understand, any source/ref for "guarddog" ?

**Comment by IceNet** [comment]
Oh, i forgot:
https://gist.github.com/Coresurgeon/96806bbb88bfbf4b4fff
