### ISSUE TITLE
[JOB OFFER] [PAID] Fixxing Teleporter Module

### ISSUE THREAD

**Issue by IceNet** [azerothcore/forum#47]
Hello guys

I'm looking for someone who can fix the teleporter module.

Todo:
Fix item to summon NPC (teleporter)
Fix gossip on NPC

It's a paid job ($20 or more, depends on the work)

Module: https://mega.nz/#!H01BXAqI!ODhWwZFc-5lnDKWu0qmVQfDkvSPrbwuZGuXvu1d3YNo

Discord:  IceNet#3553

**Comment by poszer** [comment]
Done. Check your private message on discord
