### ISSUE TITLE
Compile error, look for all dependent environment installation preparation and teacher's detailed compilation guidance

### ISSUE THREAD

**Issue by Orangeat** [azerothcore/forum#51]
Seek help! I installed according to wiki, but it was always compilation failure. What did I do wrong? I hope you can help me. Thank
I'm following the wiki dependent environment:

1: visual studio2017

2: MySQL 5.6.4

3: OpenSSL 1.0.2t 64bit

4: cmake 3.15.4

5: git 2.23.0

Windows 10 64bit Pro
15 > D: \ azerothcore WotLK \ SRC \ server \ game \ entities \ creation \ creationgroups.cpp: warning c4819: this file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss

15 > D: \ azerothcore WotLK \ SRC \ server \ game \ server \ worldsocket.cpp (727): warning c4715: "worldsocket:: processincoming": not all control paths return values

15 > game.vcxproj - > D: \ build \ SRC \ server \ game \ release \ game.lib

15 > finished generating project "game. Vcxproj".

22 > ------ rebuild all started: Project: worldserver, configuration: release x64------

22 > generating cxx prefix header D: \ build \ SRC \ server \ worldserver \ release \ cotire \ worldserver? Cxx? Prefix.hxx

22 > warn about uninitialized values.

22 > -- D: / xerothcore WotLK / DEPs / composite / cmake / composite. Cmake composite D: / build / SRC / server / worldserver / worldserver ﹣ cxx ﹣ release ﹣ composite. Cmake D: / build / SRC / server / worldserver / release / composite / worldserver ﹣ cxx ﹣ prefix. Hxx D: / xerothcore WotLK / SRC / server / worldserver / precompiledheaders / worldpch. H

22 > ifdef > cplusplus

22 > "include" D: \ azerothcore WotLK \ SRC \ server \ worldserver \ precompiledheaders \ worldpch. H "

22>#endif

22>

22 > -- / * cotire.cmake 1.8.0 generated file*/

22 > / * D: / build / SRC / server / worldserver / release / cotire / worldserver? Cxx? Prefix.hxx*/

22 > ifdef > cplusplus

22 > "include" D: \ azerothcore WotLK \ SRC \ server \ worldserver \ precompiledheaders \ worldpch. H "

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp: warning c4819: this file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss

22 > rasocket.cpp

22 > tcsoap.cpp

22 > worldrunnable.cpp

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (121): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (125): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (127): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (127): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (129): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > finished generating project "worldserver. Vcxproj" - failed.

23 > ------ rebuild all started: Project: all build, configuration: release x64------

23 > building custom rule D: / azerothcore-wotlk/cmakelists.txt

==========Rebuild all: 16 succeeded, 7 failed, 0 skipped==========
Do I lack other environmental dependence? Or the source code? I hope the friends who compiled successfully can help me and let me enjoy it. I have experienced five days and nights of despair.

**Comment by FrancescoBorzi** [comment]
@Orangeat can you please read https://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by FrancescoBorzi** [comment]
![image](https://user-images.githubusercontent.com/75517/67479745-0227ce80-f65f-11e9-8a08-07dfde21d9ab.png)
