### ISSUE TITLE
[SUGGESTION] LUA Script Catalogue

### ISSUE THREAD

**Issue by ghost** [azerothcore/forum#57]
Create a catalogue, a bit like the module catalogue but for LUA scripts.

Complete and useful LUA scripts, such as systems of the type (EXP Rates Modifier etc.)

This would highlight the creations of LUA developers and avoid having to share links everywhere to external githubs.

All updated scripts would be centralized and we would know where to look for a lua script.

With always the same prerequisites as for the modules, update your script, make a complete description, screenshots etc.

If this is implemented, it might be interesting to set up a "standard" for using databases when storing data via the LUA.

Why not add a database when the Eluna module is in core, dedicated to LUA data storage.

For example I create an EXP rates modifier, I will use a DB dedicated to Eluna, create a table named mod_exp_modify and do not pollute the characters DB which could avoid some problems when updating the db's.

It needs to be optimized, but the idea is there.

**Comment by Helias** [comment]
Open-wow, I don't use much LUA, but I like your idea, I think that you can add sql in the mod-eluna, so you can make a new table structure for this, may you can define the db structure in this thread.

About script-catalogue, the current modules-catalogue is now a generic "azerothcore catalogue" which contains modules and web tools now, I can add the "script" tab in this way for LUA script ;-).

![immagine](https://user-images.githubusercontent.com/519778/70271779-5ddd8f80-17a7-11ea-8488-51eae1551c1f.png)

Just need to get some approves here and I will.
Any script need to be forked into the azerothcore github organization with a specific topic like "ac-lua" or "core-script" (suggest a better one :sweat_smile: ).

**Comment by BarbzYHOOL** [comment]
I agree it is interesting

and yes the tag is a problem imo, because "core-module" is actually a very bad tag name lol

`ac-lua` or `acore-lua` might be good

**Comment by BarbzYHOOL** [comment]
tab name: `Lua scripts` (because it can only be scripts, right ??)
tag name: `azerothcore-lua`

**Comment by iThorgrim-hub** [comment]
Yes only script LUA

It is necessary to set up a directive line to follow when SQL queries are made in order not to pollute the CA DBs.

For example, set up a DB that would always have the same name.

world = ac_world
auth = ........
AND 
eluna = ac_eluna

This could avoid damaging azerothcore's official db tables, so of course this official db would only be set up for people who have the Eluna module.

**Comment by BarbzYHOOL** [comment]
for that, it will require to create a default "lua script" template, pretty much like https://github.com/azerothcore/skeleton-module/ and maybe a small script to initiate a script (maybe to put in mod-eluna repository)

**Comment by Shard-MW** [comment]
This is a great idea. I'll share my tools and scripts too when the lua scripts catalogue will be there :)

**Comment by iThorgrim-hub** [comment]
#Little up

**Comment by Helias** [comment]
Lua Script tab added http://www.azerothcore.org/modules-catalogue/

**Comment by BarbzYHOOL** [comment]
ok, todo we need to improve this page (i see wrong stuff written here) http://www.azerothcore.org/modules-catalogue/submit.html and also allow people to submit lua script repo but let's first see what ithorgrim wants to share xD

**Comment by Helias** [comment]
I tried to refact the code that we need to refact, but I think that I will re-make it from scratch in future.
