### ISSUE TITLE
[TOOL]Are there any website for player to register a user from internet.

### ISSUE THREAD

**Issue by wplatform** [azerothcore/forum#64]
I am looking for a website that can let the player register a user from the Internet.

**Comment by pangolp** [comment]
Good morning. You have several CMS available.
Some of them are maintained by members of azerothcore, and others are external. Some of them are:
- FusionCMS
- BlizzCMS
- WowCMS
- FusionGEN

**Comment by wplatform** [comment]
Thanks, @pangolp

Good morning, I will take a look at these products. I may have to make some changes to the product let it support the Chinese.

**Comment by pangolp** [comment]
Yes, you may have to add the language configuration file to it, but most work with multiple languages.

**Comment by pangolp** [comment]
https://gitlab.com/WoW-CMS/BlizzCMS/tree/devs/application/language

That's version 1 of the cms, maybe version 2 will include the Chinese language, but I really don't know.
