### ISSUE TITLE
WorldServer Problem

### ISSUE THREAD

**Issue by QuarTz0786** [azerothcore/forum#72]
Hello guys,
I am pretty new to Linux and WoW servers. Today I've tried to setup a server, everything went smooth but for some reasons, I cannot start the WorldServer. This is what I get in console and I have no idea how to fix it:

azcore@Server:~/azeroth-server/bin$ screen -AmdS world ./worldserver
azcore@Server:~/azeroth-server/bin$ screen -r world
There is no screen to be resumed matching world.
azcore@Server:~/azeroth-server/bin$

Utill this point, everything went smooth, no errors.

I am very sorry if this was already posted or solved.

Best regards,
iTweaks

**Comment by FrancescoBorzi** [comment]
Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help

the forum is not the right place to ask for support
