### ISSUE TITLE
[DEV] ELUNA. Update in a gossip pop-up window

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/forum#80]
How can I make the pop-up update the information? If I call up a pop-up window, it is not updated. I need to make a valid timer in the pop-up window using an eluna. Can somebody help me with the code?
`player:GossipMenuAddItem(0, "|TInterface/ICONS/inv_misc_spyglass_02:30:30:-18:0|tTimer", 0, 99, false, "50 seconds")`

I need the timer to go. I have the code for the timer, but I can't update the pop-up menu.

![image](https://user-images.githubusercontent.com/16816228/76200379-b9db0880-621b-11ea-9860-f56307dbce43.png)

**Comment by BarbzYHOOL** [comment]
ask in eluna repo maybe?
