### ISSUE TITLE
CMAKE

### ISSUE THREAD

**Issue by bilbreyde** [azerothcore/forum#81]
I'm getting an error while trying to compile, the error I'm getting is OPENSSL_INCLUDE_DIR-NOTFOUND. this seems fairly straight forward but I can't seem to resolve the issue.

Here are some details I hope help shed some light.

Windows 10 Pro
CMake version is 3.16.5
I've tried installing both
Win64OpenSSL-1_0_2u
and
Win64OpenSSL-1_1_d
(Uninstalled old version before re-installing) tried both default windows directory and /bin on both still getting this error no matter what

CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  src/cmake/macros/FindOpenSSL.cmake:184 (find_package_handle_standard_args)
  deps/openssl/CMakeLists.txt:17 (find_package)

**Comment by FrancescoBorzi** [comment]
the forum is not the best place to ask for support, please read:

https://www.azerothcore.org/wiki/How-to-ask-for-help
