### ISSUE TITLE
[TOOL] TemplateNPC-azerothcore

### ISSUE THREAD

**Issue by cm86** [azerothcore/forum#89]
Hello together,
What have I Todo, to get this to work with my private server in docker!?

I have already tried these steps:
- download in the modules directory
- rebuild the containers
- import the sql-files
- start the server

But there is no NPC in the game...

The modules is located here
https://github.com/azerothcore/mod-npc-talent-template

Mfg chris

**Comment by BarbzYHOOL** [comment]
verify you have this ID in creature_template 55002 then spawn it

why not open the issue in corresponding repository though?

**Comment by cm86** [comment]
Hello and thanks for the reply.
i have opend an issue in the responding repository. but i thought here i will get faster reply...

i have verified that the creature is the db... 
![grafik](https://user-images.githubusercontent.com/14919688/78165439-9dfa0980-744b-11ea-8d88-b4a2672e23a6.png)

and i have tried to spawn the npc with ```.npc add 55002``` (in the game)
but here i get the answer:
- ```there is no such subcommand```

so maybe there is another way to spawn the npc?

mfg Chris

**Comment by BarbzYHOOL** [comment]
no, you have a problem in your DB or core if you can't use this command, you didn't install properly

In fact, I feel like you don't have enough permission to use the command, use a rank 3+ account

**Comment by cm86** [comment]
So your were right. I moved the gmlevel of the account to 3 and then i could spawn the npc...
thanks in advance
