### ISSUE TITLE
I want to use azerothcore-wotlk as my server and some lnowleges want to know.

### ISSUE THREAD

**Issue by wplatform** [azerothcore/forum#93]
Is The Wintergrasp available?
Is The Trial of the Champion available?
How many players can support online on one server?(4G memory)?
How to port the trinitycore db into azerothcore-wotlk?

**Comment by Helias** [comment]
About migrating TC -> AC you could use this https://github.com/azerothcore/tool-tc-migration, it's experimental, make a backup and do some tests before using for production

**Comment by FrancescoBorzi** [comment]
> Is The Wintergrasp available?

yes

> Is The Trial of the Champion available?

yes 

> How many players can support online on one server?(4G memory)?

http://www.azerothcore.org/wiki/Memory-Usage

> How to port the trinitycore db into azerothcore-wotlk?

https://github.com/azerothcore/tool-tc-migration

**Comment by Viste** [comment]
lol how many time you ask this again
https://github.com/azerothcore/azerothcore-wotlk/issues/2906

**Comment by wplatform** [comment]
Sorry, I thought this question would be closed since it doesn't conform to the issue template. The support is very friendly.

**Comment by wplatform** [comment]
Can you tell me how many players can support online on my server(with 2cpu and 4G RAM). I see the Memory-Usage doc !6G just can support 100 players.

**Comment by BarbzYHOOL** [comment]
4GB ram is really SMALL

**Comment by Viste** [comment]
PreloadAllNonInstancedMapGrids = 0 and you can run 30-50 player in 40 GB but if you dont have any apache on this machine only mysql and world auth servers 
for 100 players need 6GB

**Comment by BarbzYHOOL** [comment]
yes, you will have to reboot the server often :D

**Comment by wplatform** [comment]
Apache, Mysql, Auth, World process is run together on one server. I have limited the apache memory usage. I will fell so pain if the server reboot often.  how often How memory is needed to support 2000+ players online. I have encountered the same issue on TrinityCore. the world process is killed by Linux. The 'dmesg' can show the killed log, but not frequently.  I want to know how often reboot the server on Azerothcore.

**Comment by BarbzYHOOL** [comment]
>How memory is needed to support 2000+ players online

:rofl:

if you load all the maps, you will need 12GB minimum, with 0 players http://www.azerothcore.org/wiki/Memory-Usage that's coming from people who tested like Viste, Stoabrogga

So with 2000 players, you better have much more, like 32GB or 64GB

**Comment by wplatform** [comment]
Oh my god,  I max memory computer I can buy on cloud is 16GB. so, it only supports 100 players? How about trinity core?

**Comment by Viste** [comment]
16GB with world auth and mysql can easy support 500-1000 players )
about trinitycore ask them plz we can answer but its not out duty.

**Comment by wplatform** [comment]
OK, Can the 4G server support the 200 players? I used to TrinityCore as my server, but some game feature is missed.  so I want to replace it with azerothcore-wotlk. Let me have a try.

**Comment by Viste** [comment]
I'm tired. No 4GB IS TO LOW . Because all preloaded npc transport maps etc. take up ~12GB of RAM.
and if you dont preload it when player apper on map instance and etc THEY BE LOADED TO RAM and in some moment your server be killed by linux OOMkiller becaus 4GB is to low and with 200 player this moment will come very quickly.

**Comment by BarbzYHOOL** [comment]
yes, viste is right on everything

200 players will quickly visit many maps and it will use a lot of ram

**Comment by wplatform** [comment]
I have a conclusion that I need not try if I don't have 16RAM. Thanks to all of the people who answered this question and given me a lot of support.

**Comment by BarbzYHOOL** [comment]
yes
