### ISSUE TITLE
[TOOL]transfer from trinity to azerothcore, help

### ISSUE THREAD

**Issue by chamorrorenzo** [azerothcore/forum#94]
Hello, I want to merge to azerothcore from trinity with all the accounts and character on my server, is there a tool to make the merge smooth or do you a guide or any tips or healp with it

Thank you

**Comment by Kitzunu** [comment]
Hello!

Well, there is this tool https://github.com/azerothcore/tool-tc-migration but it is experimental and I cannot assure it will work...

Back up your DB before using this :)

**Comment by chamorrorenzo** [comment]
> 
> 
> Hello!
> 
> Well, there is this tool https://github.com/azerothcore/tool-tc-migration but it is experimental and I cannot assure it will work...
> 
> Back up your DB before using this :)

I will try thanks, hopefully it will work fine, im ready to get here =)

**Comment by BarbzYHOOL** [comment]
If it works fine, please repost the question on stackoverflow with tag azerothcore and answer your own question at the same time, so it can help others

**Comment by Helias** [comment]
@chamorrorenzo any feedback about that tool? I never used it, but I am curios if it satisfy everything for the migration.
