### ISSUE TITLE
[JOB OFFER] Looking for a dev to implement the dbc<->sql system

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/forum#98]
I would like to hire a developer to solve this issue with this solution: https://github.com/azerothcore/azerothcore-wotlk/issues/584#issuecomment-341962030

I know exactly how it should be but I don't have the time actually

If someone is interested please reply here, contact me or tag me on our discord channels to make an agreement for it.

Requirements:

- Good knowledges of C++ and SQL
- Good knowledge of the AzerothCore system

PLUS: if you've already contributed to AzerothCore, I'm more oriented to people that already showed their skills here.

**Comment by mishaparem** [comment]
I am interested. Please contact me. Best regards, Misha.

**Comment by Yehonal** [comment]
Hi @mishaparem , can you contact me on discord please?

**Comment by Yehonal** [comment]
Yehonal#4265

**Comment by Yehonal** [comment]
@Winfidonarleyan is working on it :) https://github.com/azerothcore/azerothcore-wotlk/pull/3002

**Comment by FrancescoBorzi** [comment]
this job is not fully DONE as:

- there are still pending fixes to be merged
- it's still not clear how to use the new system for servers that implemented customisations in their DBC
- there is no documentation explaining how to use old DBC vs new DBC-DB way

please @Winfidonarleyan and @Yehonal keep working on it
